### ISSUE TITLE
I did a thing! "Self praise"

### ISSUE THREAD

**Issue by kristoferlund** [CommonsBuild/praise_frontend#21] opened 2021-11-11 14:45 UTC
Could this be a separate bot command?

`/didathing installed the praise bot`

**Comment by Vyvy-vi** [comment] 2022-04-12 20:22
Would the API treat self-praise similar to normal praise?

**Comment by Vyvy-vi** [comment] 2022-04-12 20:31
duplicate of https://github.com/CommonsBuild/praise/issues/132

**Closed** 2022-04-12 20:30 UTC
Labels: enhancement
